#!/usr/bin/env bash

PORT=4000
ENTRYPOINT=dev.php
REMOTE=s11
DOMAIN=git.dupunkto.org

DEPLOY="rsync -ciavuP --delete --exclude .git"

# Configure the PHP server to start two
# concurrent threads.
export PHP_CLI_SERVER_WORKERS=2
export SCAN_PATH="$HOME/downloads/git-backup.old"

serve() {
  php -S 0.0.0.0:$PORT $ENTRYPOINT
}

deploy() {
  $DEPLOY . $REMOTE:domains/$DOMAIN/public_html
}