#!/usr/bin/env bash

use php

export SCAN_PATH="$HOME/downloads/git"

set -a
source "$(pwd)/.env"
set +a

PORT=4000
ENTRYPOINT=dev.php

serve() {
  php -S 0.0.0.0:$PORT $ENTRYPOINT
}

deploy() {
  lift deploy
}